name: Build and Upload Artifact
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Create a simple file
      run: |
        mkdir build
        echo "Hello, World! Built on $(date)" > build/hello.txt
        echo "This is my artifact content" > build/output.txt
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-files
        path: build/
