name: Create Release with Artifact
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build project
      run: |
        mkdir release
        echo "Release version: ${GITHUB_REF#refs/tags/}" > release/version.txt
        zip -r project-release.zip release/
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: project-release.zip
        name: Release ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
